# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Always on the Way
subtitle: Love ice cream. Love sunshine. Love life. Love the world. Love myself. Love you.
author: Jia wei
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://jevinz.github.io    # Note: don't forget to modify the CNAME file to your url
root: /
permalink: :lang/:title/
permalink_defaults:

# CDN Setting
# Docs: https://www.jsdelivr.com/?docs=gh
# If Github Pages deploy，you can ues jsdelivr settings
#
jsdelivr:
  jsdelivr_url: https://cdn.jsdelivr.net/gh/
  github_username: JevinZ
# Custom Setting Start

# Site settings
SEOTitle: Always on the way
# email: hexo-theme-livemylife@gmail.com
# description: "It's an IT blog..."
# keyword: "v-vincen,v-vincen,livemylife,IT  blog,Blog"
header-img: img/header_img/newhome_bg.jpg
archives-img: img/header_img/archive_bg2.jpg


# Favicon settings
favicon: img/avatar/roguerabbit.jpg


# Signature Setup
signature: true # show signature
signature-img: img/signature/jiawei.png


# Wave settings
wave: true


# SNS Settings
# RSS: true
github_username: JevinZ
# twitter_username: V_Vincen_
# instagram_username: v_vincen_
# facebook_username:  yourAccount
# linkedin_username:  yourAccount
# zhihu_username: WVincen
# weibo_username: WVincen


# Sidebar Settings
sidebar: true   # whether or not using Sidebar.
sidebar-about-description: "心灵纯洁的人，生活充满甜蜜和喜悦。"
sidebar-avatar: img/avatar/pika.jpg    # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- visitor   # busuanzi: https://busuanzi.ibruce.info/
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
- category


# widget behavior
## Archive
archive_type: 'monthly'
show_count: true

## Featured Tags
featured-tags: true   # whether or not using Feature-Tags
featured-condition-size: 0    # A tag will be featured if the size of it is more than this condition value

## Friends
friends: [
    {
        title: "Hexo",
        href: "https://hexo.io/"
    }
]


# Comment Settings

## Gitalk Settings
## Doc:https://github.com/gitalk/gitalk/blob/master/readme-cn.md

# Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:


# Writing
new_post_name: :title.md    # File name of new posts
default_layout: post
auto_spacing: true
titlecase: false    # Transform title into titlecase
# New option
# https://hexo.io/docs/configuration.html#Writing
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''


# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true    # show posts tags


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
##
date_format: YYYY-MM-DD
time_format: HH:mm:ss
# New option
# https://hexo.io/docs/configuration#Date-Time-format
updated_option: date


# Pagination
## Set per_page to 0 to disable pagination
##
per_page: 10
pagination_dir: archives

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
##
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'


# Build Settings
anchorjs: true    # if you want to customize anchor. check out line:26 of `anchorjs.ejs`


# article top
top: true


# WordCount Settings
## Dependencies: https://github.com/willin/hexo-wordcount
## Docs: https://www.npmjs.com/package/hexo-wordcount
##
wordcount: true


# Busuanzi Settings
## Dependencies: https://busuanzi.ibruce.info/
## Docs: https://ibruce.info/
busuanzi: true


# top scroll progress
scroll: true


# Tip
tip:
  enable: true
  # copyright: If you like this blog or find it useful for you, you are welcome to comment on it. You are also welcome to share this blog, so that more people can participate in it. If the images used in the blog infringe your copyright, please contact the author to delete them. Thank you !


# Social Share Post
## Docs:https://github.com/overtrue/share.js
##
socialshare: true


# Viewer config
## Docs:https://github.com/fengyuanchen/viewer
## Demo:https://fengyuanchen.github.io/viewer/
##
viewer: true


# ThemeColor config
themecolor:
  enable: true
  mode: light # themecolor mode light or dark, default light


# Mouseclick config
mouseclick:
  enable: true
  content:
    - 执子之手，与子偕老...
    - 你若安好，便是晴天...
    - 大学之道，在明明德...
    - 高山仰止，景行行之...
    - 青青子衿，悠悠我心...
    - 如切如磋，如琢如磨...
    - 它山之石，可以攻玉...
    - 投我以桃，报之以李...
    - 知我者谓我心忧，不知我者谓我何求...
  color:
    - '#9933CC'
    - '#339933'
    - '#66CCCC'
    - '#FF99CC'
    - '#CCCCFF'
    - '#6666CC'
    - '#663399'
    - '#66CC99'
    - '#FF0033'


# Ribbon config
ribbonDynamic: true


# Line config
bglinecanvas: false  # The special effects will take up a lot of cpu resorces, please open it carefully.


# Search Setting
## Search: https://go.kieran.top/post/45/
## Dependencies: https://github.com/V-Vincen/hexo-generator-zip-search
##
search:
  path: search.json
  zipPath: search.flv
  versionPath: searchVersion.json
  field: post
  trigger: auto   # if 'auto', trigger search by changing input;if 'manual', trigger search by pressing enter key or search button
  top_n_per_article: 1    # show top n results per article, show all results by setting to -1


# Theme config
## Themes: https://hexo.io/themes/
##
theme: livemylife


# Gitter
## Docs:https://gitter.im/?utm_source=left-menu-logo
##
gitter:
  room: your-community/your-room


# Deployment
## Docs: https://hexo.io/docs/deployment.html
##
deploy:
  type: git
  repo: https://github.com/JevinZ/JevinZ.github.io.git
  branch: master
